### ISSUE TITLE
Error writing Capytaine data to hyddb1

### ISSUE THREAD

**Issue by mancellin** [RubendeBruin/pymeshup#3]
When running the standalone executable linked in https://github.com/capytaine/capytaine/discussions/372, I get the following error message in the console:
```
Traceback (most recent call last):
  File "pymeshup\gui\main.py", line 271, in <lambda>
  File "pymeshup\gui\main.py", line 326, in run_captyaine
  File "pymeshup\gui\capytaine_runner.py", line 76, in run_capytaine
  File "mafredo\hyddb1.py", line 206, in save_as
  File "xarray\core\dataarray.py", line 3978, in to_netcdf
  File "xarray\backends\api.py", line 1229, in to_netcdf
  File "xarray\backends\scipy_.py", line 138, in __init__
ValueError: cannot save to a group with the scipy.io.netcdf backend
```

**Comment by RubendeBruin** [comment]
<img width="524" alt="image" src="https://github.com/RubendeBruin/pymeshup/assets/34062862/e9c81dbe-85b9-4b0d-8050-be43b010c93b">

confirmed on my machine
